### ISSUE TITLE
+ csv upload to github cronjob

### ISSUE THREAD

**Issue by 7yl4r** [dotis/FGBNMS_DBv3#15]
1. [x] create new repo for the csv data `extracted_sat_ts_gom_csv_data`: 
  * [here](https://github.com/7yl4r/extracted_sat_ts_gom_csv_data)
3. [x] create & connect local repo to github `cd /srv/[...] && git init && git remote set-url github[..]`
5. [x] create crontab to update csv files in github

For Dan's crontab:

```bash
cd /srv/imars-objects/fgb/EXT_TS_MODA/OC && \
  git add FGBdbv2_chlor_a_TS_MODA_daily_EFG.csv && \
  git commit -m 'auto-upload csv files' && \
  git push
```

**Comment by 7yl4r** [comment]
@dotis : I set up the repo and add the following to your crontab:

```crontab
# === upload csv extraction files to github
0 8 * * * /bin/bash /srv/imars-objects/fgb/EXT_TS_MODA/OC/upload_files.sh
```

The script there should work after:
  * [ ] you accept the collaborator invite to the repo through github
  * [ ] the following is run manually on seashell to set up the remote `cd /srv/imars-objects/fgb/EXT_TS_MODA/OC && git push -u origin main`

I am assuming your `seashell:~/.ssh/id_rsa.pub` is already added to github. If we get permissions errors you will need to add that through the github settings.

**Comment by dotis** [comment]
fatal: Not a git repository (or any parent up to mount point /srv/imars-objects)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

It looks like I need to add it. I don't see "settings". Maybe @7yl4r needs to do that.
________________________________

**Comment by dotis** [comment]
I was using the wrong directory. Now getting this:

Warning: Permanently added the RSA host key for IP address '140.82.114.3' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.


________________________________

**Comment by 7yl4r** [comment]
once we set up your ssh key with github we can try again.

**Comment by dotis** [comment]
I set up the key and tried the git push again, but it seems the key is the wrong type:

Warning: Permanently added the RSA host key for IP address '140.82.114.4' to the list of known hosts.
ERROR: You're using an RSA key with SHA-1, which is no longer allowed. Please use a newer client or a different key type.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.

________________________________

**Comment by 7yl4r** [comment]
It is looking more and more like GitHub's management is making things hard on everyone not using vscode. Next they will get people onto vscode subscriptions. :roll_eyes: I forsee a switch over to GitLab on the way for me.

I put the crontab on manglillo instead of seashell. Seashell is past end-of-life and getting the newer stuff working is a pain.
